### ISSUE TITLE
Package Reducer / choco optimize - not working in some cases

### ISSUE THREAD

**Issue by mmundy1** [chocolatey/chocolatey-licensed-issues#202]
### What You Are Seeing?
After downloading and recompiling sql-server-2017-cumulative-update, the binaries are still present even when it should be optimized.
sql-server-management-studio appears to exhibit similar behavior.

### What is Expected?
After sql-server-2017-cumulative-update is installed from a localized package, the .exe is no longer present in the package folder.

### How Did You Get This To Happen? (Steps to Reproduce)
0) set choco features with

```yaml
- name: Ensure Chocolatey Features
  win_chocolatey_feature:   
    name: "{{ item.name }}"   
    state: "{{ item.state }}"   
  loop:

- name: downloadCache
  state: disabled

- name: reduceInstalledPackageSpaceUsage
  state: enabled

- name: useFIPSCompliantChecksums
  state: enabled
```

1) download and recompile package from https://chocolatey.org/packages/sql-server-2017-cumulative-update
2) upload to local chocolatey server
3) install via win_chocolatey
4) see files still present in directory
  Directory: C:\ProgramData\chocolatey\lib\sql-server-2017-cumulative-update\tools
Mode                LastWriteTime         Length Name

- - -
d-----        2/10/2021   6:31 PM                files
-a----        2/10/2021   6:31 PM           1844 chocolateyinstall.ps1
**-a----        2/10/2021   6:31 PM      559201160 SQLServer2017-KB4577467-x64.exe**
-a----        2/10/2021   6:35 PM              0 SQLServer2017-KB4577467-x64.exe.ignore

Note: running 'choco optimize' manually does not correct the issue either.

### References

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/423) by [Unito](https://www.unito.io)
┆Milestone: 7.0.0
